In [2]:
import pandas as pd
import seaborn as sns
df=pd.read_csv("building-points.csv",delimiter=';', skiprows=0, low_memory=False)
df.head()

,pin,owner,owner2,owneradd1,owneradd2,owneradd3,location,building_type,building_sub_type,bldgstyle,...,streetnumber,streetmisc,streetprefix,streetname,streettype,streetsuffix,phycity,phyzip,geo_shape,geo_point_2d
0,7.641434e+10,GINKGO BVG LLC,NaN,GINKGO RESIDENTIAL LLC,1023 W MOREHEAD STE STE 301,CHARLOTTE NC 28208,200 ELDERBERRY HILL CT,Apartment,Townhouse,Townhouse,...,200.0,NaN,NaN,ELDERBERRY HILL,CT,NaN,CARY,27513.0,"{""type"": ""Point"", ""coordinates"": [-78.78730672...","35.7952566951, -78.7873067278"
1,7.641443e+10,"CIMATO, BRETT TRUSTEE","JONES, SHANNON TRUSTEE",600 N HARRISON AVE,CARY NC 27513-4607,NaN,600 N HARRISON AVE,Residential,2 Family,Split Level,...,600.0,NaN,N,HARRISON,AVE,NaN,CARY,27513.0,"{""type"": ""Point"", ""coordinates"": [-78.78285938...","35.7938202579, -78.7828593888"
2,7.641972e+10,JORDAN REAL ESTATE HOLDINGS LLC,NaN,PO BOX 4422,CARY NC 27519-4422,NaN,407 E CHATHAM ST,Retail,Single Tenant,Conventional,...,407.0,NaN,E,CHATHAM,ST,NaN,CARY,27511.0,"{""type"": ""Point"", ""coordinates"": [-78.77376778...","35.7891882566, -78.7737677869"
3,7.641721e+10,WALKER & WEST FAMILY PROPERTIES LLC,NaN,930 SE MAYNARD RD,CARY NC 27511-4208,NaN,411 W CHATHAM ST,Industrial,Prefab. Warehouse,Conventional,...,411.0,NaN,W,CHATHAM,ST,NaN,CARY,27511.0,"{""type"": ""Point"", ""coordinates"": [-78.78948847...","35.7861944022, -78.7894884711"
4,7.641721e+10,WALKER & WEST FAMILY PROPERTIES LLC,NaN,930 SE MAYNARD RD,CARY NC 27511-4208,NaN,413 W CHATHAM ST,Industrial,Prefab. Warehouse,Conventional,...,413.0,NaN,W,CHATHAM,ST,NaN,CARY,27511.0,"{""type"": ""Point"", ""coordinates"": [-78.78948847...","35.7861944022, -78.7894884711"

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 189039 entries, 0 to 189038
Data columns (total 37 columns):
pin                  189039 non-null float64
owner                189039 non-null object
owner2               35466 non-null object
owneradd1            189039 non-null object
owneradd2            189018 non-null object
owneradd3            6314 non-null object
location             189039 non-null object
building_type        189038 non-null object
building_sub_type    184900 non-null object
bldgstyle            175134 non-null object
yearbuilt            177467 non-null float64
units                189039 non-null float64
sqft                 189039 non-null float64
rooms                189039 non-null float64
storyheight          163074 non-null object
rooftype             0 non-null float64
roof_floorsys        13796 non-null object
extwall              176720 non-null object
basement             148221 non-null object
percentbasement      189039 non-null float64
bathrooms            176691 non-null object
bldgvalue            189039 non-null float64
utilities            176268 non-null object
realid               189039 non-null int64
additionyr           189039 non-null float64
effectiveyr          189039 non-null float64
remodelyr            189039 non-null float64
streetnumber         189032 non-null float64
streetmisc           7019 non-null object
streetprefix         5169 non-null object
streetname           189039 non-null object
streettype           185558 non-null object
streetsuffix         510 non-null object
phycity              177445 non-null object
phyzip               177410 non-null float64
geo_shape            189039 non-null object
geo_point_2d         189039 non-null object
dtypes: float64(13), int64(1), object(23)
memory usage: 53.4+ MB

In [10]:
df=df.drop(["pin","owner2"],axis=1)
df.head()

,owner,owneradd1,owneradd2,owneradd3,location,building_type,building_sub_type,bldgstyle,yearbuilt,units,...,streetnumber,streetmisc,streetprefix,streetname,streettype,streetsuffix,phycity,phyzip,geo_shape,geo_point_2d
0,GINKGO BVG LLC,GINKGO RESIDENTIAL LLC,1023 W MOREHEAD STE STE 301,CHARLOTTE NC 28208,200 ELDERBERRY HILL CT,Apartment,Townhouse,Townhouse,1999.0,6.0,...,200.0,NaN,NaN,ELDERBERRY HILL,CT,NaN,CARY,27513.0,"{""type"": ""Point"", ""coordinates"": [-78.78730672...","35.7952566951, -78.7873067278"
1,"CIMATO, BRETT TRUSTEE",600 N HARRISON AVE,CARY NC 27513-4607,NaN,600 N HARRISON AVE,Residential,2 Family,Split Level,1960.0,2.0,...,600.0,NaN,N,HARRISON,AVE,NaN,CARY,27513.0,"{""type"": ""Point"", ""coordinates"": [-78.78285938...","35.7938202579, -78.7828593888"
2,JORDAN REAL ESTATE HOLDINGS LLC,PO BOX 4422,CARY NC 27519-4422,NaN,407 E CHATHAM ST,Retail,Single Tenant,Conventional,1961.0,0.0,...,407.0,NaN,E,CHATHAM,ST,NaN,CARY,27511.0,"{""type"": ""Point"", ""coordinates"": [-78.77376778...","35.7891882566, -78.7737677869"
3,WALKER & WEST FAMILY PROPERTIES LLC,930 SE MAYNARD RD,CARY NC 27511-4208,NaN,411 W CHATHAM ST,Industrial,Prefab. Warehouse,Conventional,1979.0,5.0,...,411.0,NaN,W,CHATHAM,ST,NaN,CARY,27511.0,"{""type"": ""Point"", ""coordinates"": [-78.78948847...","35.7861944022, -78.7894884711"
4,WALKER & WEST FAMILY PROPERTIES LLC,930 SE MAYNARD RD,CARY NC 27511-4208,NaN,413 W CHATHAM ST,Industrial,Prefab. Warehouse,Conventional,1985.0,1.0,...,413.0,NaN,W,CHATHAM,ST,NaN,CARY,27511.0,"{""type"": ""Point"", ""coordinates"": [-78.78948847...","35.7861944022, -78.7894884711"

In [11]:
df=df.drop(["owneradd3","streetmisc","streetsuffix","geo_shape","geo_point_2d"],axis=1)
df.head()

,owner,owneradd1,owneradd2,location,building_type,building_sub_type,bldgstyle,yearbuilt,units,sqft,...,realid,additionyr,effectiveyr,remodelyr,streetnumber,streetprefix,streetname,streettype,phycity,phyzip
0,GINKGO BVG LLC,GINKGO RESIDENTIAL LLC,1023 W MOREHEAD STE STE 301,200 ELDERBERRY HILL CT,Apartment,Townhouse,Townhouse,1999.0,6.0,7280.0,...,37845,0.0,1999.0,0.0,200.0,NaN,ELDERBERRY HILL,CT,CARY,27513.0
1,"CIMATO, BRETT TRUSTEE",600 N HARRISON AVE,CARY NC 27513-4607,600 N HARRISON AVE,Residential,2 Family,Split Level,1960.0,2.0,2982.0,...,37847,0.0,1965.0,0.0,600.0,N,HARRISON,AVE,CARY,27513.0
2,JORDAN REAL ESTATE HOLDINGS LLC,PO BOX 4422,CARY NC 27519-4422,407 E CHATHAM ST,Retail,Single Tenant,Conventional,1961.0,0.0,3224.0,...,37866,0.0,1976.0,0.0,407.0,E,CHATHAM,ST,CARY,27511.0
3,WALKER & WEST FAMILY PROPERTIES LLC,930 SE MAYNARD RD,CARY NC 27511-4208,411 W CHATHAM ST,Industrial,Prefab. Warehouse,Conventional,1979.0,5.0,6000.0,...,37869,0.0,1979.0,0.0,411.0,W,CHATHAM,ST,CARY,27511.0
4,WALKER & WEST FAMILY PROPERTIES LLC,930 SE MAYNARD RD,CARY NC 27511-4208,413 W CHATHAM ST,Industrial,Prefab. Warehouse,Conventional,1985.0,1.0,10390.0,...,37869,0.0,1985.0,0.0,413.0,W,CHATHAM,ST,CARY,27511.0

In [12]:
df=df.drop(["streetprefix","owneradd2","location","building_sub_type","rooftype","roof_floorsys","building_type","extwall","utilities","streettype","owneradd1","bathrooms","bldgstyle","basement","remodelyr","streetnumber","streetname","phycity","phyzip","storyheight"],axis=1)
df.head()

,owner,yearbuilt,units,sqft,rooms,percentbasement,bldgvalue,realid,additionyr,effectiveyr
0,GINKGO BVG LLC,1999.0,6.0,7280.0,0.0,0.0,13114880.0,37845,0.0,1999.0
1,"CIMATO, BRETT TRUSTEE",1960.0,2.0,2982.0,0.0,50.0,146396.0,37847,0.0,1965.0
2,JORDAN REAL ESTATE HOLDINGS LLC,1961.0,0.0,3224.0,0.0,0.0,95484.0,37866,0.0,1976.0
3,WALKER & WEST FAMILY PROPERTIES LLC,1979.0,5.0,6000.0,0.0,0.0,454607.0,37869,0.0,1979.0
4,WALKER & WEST FAMILY PROPERTIES LLC,1985.0,1.0,10390.0,0.0,0.0,454607.0,37869,0.0,1985.0

In [13]:
from sklearn.preprocessing import LabelEncoder
model=LabelEncoder()
df.owner=model.fit_transform(df.owner)
df.head()

,owner,yearbuilt,units,sqft,rooms,percentbasement,bldgvalue,realid,additionyr,effectiveyr
0,52828,1999.0,6.0,7280.0,0.0,0.0,13114880.0,37845,0.0,1999.0
1,27407,1960.0,2.0,2982.0,0.0,50.0,146396.0,37847,0.0,1965.0
2,73863,1961.0,0.0,3224.0,0.0,0.0,95484.0,37866,0.0,1976.0
3,154502,1979.0,5.0,6000.0,0.0,0.0,454607.0,37869,0.0,1979.0
4,154502,1985.0,1.0,10390.0,0.0,0.0,454607.0,37869,0.0,1985.0

In [14]:
median=df.yearbuilt.median()

In [15]:
df.yearbuilt.fillna(median)
df.yearbuilt=df.yearbuilt.fillna(median)

In [16]:
median=df.units.median()

In [17]:
df.units.fillna(median)
df.units=df.units.fillna(median)

In [18]:
median=df.sqft.median()
df.sqft.fillna(median)
df.sqft=df.sqft.fillna(median)

In [19]:
median=df.rooms.median()
df.rooms.fillna(median)
df.rooms=df.rooms.fillna(median)

In [20]:
median=df.rooms.median()
df.rooms.fillna(median)
df.rooms=df.rooms.fillna(median)

In [21]:
median=df.rooms.median()
df.rooms.fillna(median)
df.rooms=df.rooms.fillna(median)

In [22]:
median=df.percentbasement.median()
df.percentbasement.fillna(median)
df.percentbasement=df.percentbasement.fillna(median)

In [23]:
median=df.bldgvalue.median()
df.bldgvalue.fillna(median)
df.bldgvalue=df.bldgvalue.fillna(median)

In [24]:
median=df.realid.median()
df.realid.fillna(median)
df.realid=df.realid.fillna(median)

In [25]:
median=df.additionyr.median()
df.additionyr.fillna(median)
df.additionyr=df.additionyr.fillna(median)

In [26]:
median=df.effectiveyr.median()
df.effectiveyr.fillna(median)
df.effectiveyr=df.effectiveyr.fillna(median)

In [27]:
x=df.drop("bldgvalue",axis=1)
y=df.bldgvalue

In [28]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1)

In [ ]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

/Users/nikhilchaudhary/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/nikhilchaudhary/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)

In [1]:
model.predict(x_test)

NameError: name 'model' is not defined